stages:
  - build

variables:
  REGISTRY_HOST: "https://index.docker.io/v1/"
  IMAGE_NAME: "docker.io/daiz123d/tesst"
  IMAGE_TAG: "latest"

build-image:
  stage: build
  tags:
    - k8s-runner
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$REGISTRY_HOST\":{\"username\":\"$DOCKER_USER\",\"password\":\"$DOCKER_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "$CI_PROJECT_DIR" --dockerfile "$CI_PROJECT_DIR/Dockerfile" --destination "$IMAGE_NAME:$IMAGE_TAG"
  only:
    - main
