stages:
  - build

variables:
  HARBOR_REGISTRY: "harbor.tinasoft.io"
  HARBOR_PROJECT: "intern-devops"
  HARBOR_REPOSITORY: "tesst"
  HARBOR_USER: "dai.ta"
  HARBOR_PASSWORD: "Tinasoft@123"

build-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - |
      if [ -z "$HARBOR_USER" ] || [ -z "$HARBOR_PASSWORD" ]; then
        echo "Missing HARBOR_USER or HARBOR_PASSWORD"
        exit 1
      fi
    - export IMAGE_NAME="$HARBOR_REGISTRY/$HARBOR_PROJECT/$HARBOR_REPOSITORY"
    - echo "Pushing image to $IMAGE_NAME"
    - printf '{"auths":{"%s":{"username":"%s","password":"%s"}}}' "$HARBOR_REGISTRY" "$HARBOR_USER" "$HARBOR_PASSWORD" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
        --context "$CI_PROJECT_DIR" \
        --dockerfile "$CI_PROJECT_DIR/Dockerfile" \
        --destination "$IMAGE_NAME:latest" \
        --destination "$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"
  rules:
    - if: '$CI_COMMIT_BRANCH'
