apiVersion: apps/v1
kind: Deployment
metadata:
  name: weeb
  namespace: argocd
  labels:
    app: weeb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weeb
  template:
    metadata:
      labels:
        app: weeb
    spec:
      containers:
        - name: weeb
          image: 172.16.4.12:5050/dai.ta/tesst:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
