apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lll
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://172.16.4.12:8888/dai.ta/tesst.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
